""" DATA GENERATION SETTINGS"""

# Variables for KITTI File structure
MAIN_FOLDER = "./KITTI_CARLA"
TESTING_FOLDER = f"{MAIN_FOLDER}/TESTING"
TRAINING_FOLDER = f"{MAIN_FOLDER}/TRAINING"

TESTING_CALIB = f"{TESTING_FOLDER}/calib"
TRAINING_CALIB = f"{TRAINING_FOLDER}/calib"

TESTING_IMAGE = f"{TESTING_FOLDER}/image_2"
TRAINING_IMAGE = f"{TRAINING_FOLDER}/image_2"

TESTING_LIDAR = f"{TESTING_FOLDER}/velodyne"
TRAINING_LIDAR = f"{TRAINING_FOLDER}/velodyne"

TRAINING_LABELS = f"{TRAINING_FOLDER}/label_2"

# Lidar can be saved in bin to comply to kitti, or the standard .ply format
LIDAR_DATA_FORMAT = "bin"
LIDAR_PATH = "A:\\Computer Vision\\CARLA\\CARLA_0.9.13\\CARLA_0.9.13\\WindowsNoEditor\\Carla-Data-Collection\\velodyne"

OCCLUDED_VERTEX_COLOR = (255, 0, 0)
VISIBLE_VERTEX_COLOR = (0, 255, 0)

""" CARLA SETTINGS """
CAMERA_HEIGHT_POS = 1.6
LIDAR_HEIGHT_POS = CAMERA_HEIGHT_POS
MIN_BBOX_AREA_IN_PX = 100

""" AGENT SETTINGS """
NUM_VEHICLES = 20
NUM_PEDESTRIANS = 10

""" RENDERING SETTINGS """
WINDOW_WIDTH = 1248
WINDOW_HEIGHT = 384
MINI_WINDOW_WIDTH = 320
MINI_WINDOW_HEIGHT = 180

WINDOW_WIDTH_HALF = WINDOW_WIDTH / 2
WINDOW_HEIGHT_HALF = WINDOW_HEIGHT / 2

MAX_RENDER_DEPTH_IN_METERS = 70  # Meters
MIN_VISIBLE_VERTICES_FOR_RENDER = 4